services:
  - type: web
    name: gpc-automation
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python GPC_Automation.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
