services:
  - type: web
    name: gpc-automation
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python GPC_Automation.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
